### PR TITLE
Update sugar for multi-dex

### PR DESCRIPTION
**Pull request by tracytheron**
I use sugar-ORM in my project, when I enable multi-dex, not all the tables will be created. So I did some research on it and this pull request might be a solution. I tested it in my project and it works well.

### CODE REVIEW

**Comment by tracytheron** [comment]
I added some missed imports

**Comment by sibeliusseraphini** [comment]
@tracytheron could fix the conflits please?

**Comment by tracytheron** [comment]
@sibeliusseraphini  fixed

**Comment by Vookash** [comment]
How can I get this fix? I like SugarORM but his this MultiDex issue drives me nuts.

**Comment by sibeliusseraphini** [comment]
You can get the master version and use it as a module in your project

**Comment by Vookash** [comment]
Could you give me a .jar? Something it's not working for me...

**Comment by sibeliusseraphini** [comment]
I've uploaded a .jar from master here: https://www.dropbox.com/s/9z85lrud4lgiv6e/sugar-0.7.1.201405082137.jar?dl=0

**Pull request merged**
