### PR TITLE
add method afterTableCreated

### PR DESCRIPTION
**Pull request by marcusbalbi**
add method afterTableCreated that executes a sql file with the name of the domain class. 

I've added this feature after long period searching for an answer for populate the database after the table creation, so when i create a new modelm i could add a sql file with the name of the model in sugar_upgrades and it will be executed, of course i do need to create a <VERSION>.sql if i want all the apps to execute the sql files. 

i've made this feature after read the issue 87

Sorry for my english , long time no speak.

Thank you!

### CODE REVIEW

**Comment by sibeliusseraphini** [comment]
I think the script after creation of table should be store on assets like the migration scripts

https://github.com/satyan/sugar/pull/577/files#diff-90e36f87e0174df6728e723fe04cebe6L92

You should also check whether the file exist or not

could you please make these changes?

**Comment by marcusbalbi** [comment]
should i create a new folder inside  assets like "sugar_after_create" or could it stay inside sugar upgrades ?

if i put the after creation files in this new folder i couldn't use the executeScript method, should it  be refactored?

does afterTableCreated verify if the file exists and log it if it don't ? becouse executeScript have a try/catch for that. 

i can make these changes! thank you!

**Comment by JonatanSalas** [comment]
@marcusbalbi what you can do it's to modify the executeScript method and add a new param where you pass a path as String. In that way you can reuse this method. If the executeScript is private you can refactor. Do that change and I will take a look.

**Comment by sibeliusseraphini** [comment]
use another folder for after create

**Comment by JonatanSalas** [comment]
@marcusbalbi Thanks for your PR! :smile:

**Comment by marcusbalbi** [comment]
You're welcome @JonatanSalas !

it's a honor contribute to this amazing project!

thanks!

**Pull request merged**
