### PR TITLE
Implement SugarRecord.sum()

### PR DESCRIPTION
**Pull request by SiebelsTim**
analog to count()

### CODE REVIEW

**Comment by JonatanSalas** [comment]
@SiebelsTim Why don't you add some test in order to not decrease the coverage?

**Comment by SiebelsTim** [comment]
@JonatanSalas At first I didn't find tests for count-like functions. After looking thoroughly, I added some tests :)

**Comment by SiebelsTim** [comment]
Btw: Should I call `toSQLNameDefault()`around the field names, or should I let the user change it to underscores?

**Comment by sibelius** [comment]
LGTM

**Comment by sibelius** [comment]
thanks

**Comment by SiebelsTim** [comment]
Thanks :)

**Pull request merged**
