### PR TITLE
Fixed issue with database upgrade when MultiDex support is enabled.

### PR DESCRIPTION
**Pull request by bendaniel10**
Reworked the logic of classpath scanning for entity classes which occurs on database creation or update. I made use of a solution found on SO that can scan all classes in an APK with multi - dex enabled.

### CODE REVIEW

**Comment by sibeliusseraphini** [comment]
merged

**Comment by firasalkafri** [comment]
This is not working
After using multidex for my app, the library stopped picking up classes names and the only way to avoid table not found exceptions is to to create an empty record each time in the Application class.

**Comment by sibeliusseraphini** [comment]
@firasalkafri could you provide a PR to fix this?

**Comment by firasalkafri** [comment]
@sibeliusseraphini Would definitely do once I get the time...just wanted to share the problem for now in case you have a fix

**Comment by sibeliusseraphini** [comment]
@firasalkafri thanks, try to add a test case that breaks the current version as well

**Pull request merged**
