### PR TITLE
Enums serialize using .name()

### PR DESCRIPTION
**Pull request by benohalloran**
Resolves issue #300

### CODE REVIEW

**Comment by whoshuu** [comment]
Hey @benohalloran, thanks for the PR, I really appreciate it. If possible, can you write a test case that validates the behavior you're claiming here? That would speed up the process of getting this merged by many many factors.

**Comment by benohalloran** [comment]
@whoshuu I'll write some tests this afternoon and add it to the PR

**Comment by dhinx** [comment]
use type variable as enum doesn't work

`List<Customer> customers = Select.from(Customer.class).where(Condition.prop("NAME").like("%" + query + "%"))
                .or(Condition.prop("PHONE_NUMBER").like("%" + query + "%"))
                .or(Condition.prop("EMAIL").like("%" + query + "%"))
                .or(Condition.prop("ADDRESS").like("%" + query + "%"))
                .and(Condition.prop("ACTIVE_FLAG").eq(ActiveFlag.ACTIVE))
                .list();`

or with

`List<Customer> customers = Customer.find(Customer.class, "(NAME = ? OR PHONE_NUMBER = ? OR EMAIL = ? OR ADDRESS = ?) AND ACTIVE_FLAG = ?", "%" + query + "%", "%" + query + "%", "%" + query + "%", "%" + query + "%", ActiveFlag.ACTIVE.toString());`

it doesn't work. And when I realize, when sugar created table it doesn't complete. And here output of schema table

`CREATE TABLE CUSTOMER ( ID INTEGER PRIMARY KEY AUTOINCREMENT , ADDRESS TEXT, EMAIL TEXT, NAME TEXT, PHONE_NUMBER TEXT, UPDATE_DATE INTEGER NULL, ACTIVE_FLAG , CREATE_BY TEXT, CREATE_DATE INTEGER NULL, REF_ID TEXT, UPDATE_BY TEXT, TYPE INTEGER, ACTIVE INTEGER );`

**Comment by dhinx** [comment]
i have a problem.

when i query database with criteria enum and i does not work and shown zero in list

when i check table schema it shown no data type at it
`TABLE STOCK_OPNAME ( ID INTEGER PRIMARY KEY AUTOINCREMENT , BUILDING , DESCRIPTION TEXT, EMPLOYEE INTEGER, STOCK_OPNAME_STATUS , UPDATE_DATE INTEGER NULL, ACTIVE_FLAG , CREATE_BY TEXT, CREATE_DATE INTEGER NULL, REF_ID TEXT, UPDATE_BY TEXT, TYPE INTEGER, ACTIVE INTEGER );`

here is the code
`List<StockOpname> stockOpnames = Select.from(StockOpname.class)
.where(Condition.prop("STOCK_OPNAME_STATUS").eq(StockOpnameStatus.INCOMPLETE))
.orderBy("CREATE_DATE DESC").list();`

thank you

**Pull request closed without merging**
