### PR TITLE
Joda DateTime, DateMidnight, java.util.Date, java.util.Calendar

### PR DESCRIPTION
**Pull request by toadzky**
Added JodaTime library and support for their classes. Added support java.util.Calendar and changed java.util.Date so both are stored as longs.

### CODE REVIEW

**Comment by giorgioprovenzale** [comment]
Hi, how can I integrate the patch for Joda library? Thanks

**Comment by toadzky** [comment]
it's pretty out of date. i'd probably need to go through and pull it forward. once it's updated, i'll open another PR. while you are waiting for the PR to be accepted, you could download and build my fork as a jar and include it in your project.

**Comment by sibeliusseraphini** [comment]
> @toadzky I guess, Joda DateTime may not apply to all projects.. and adds a dependency for the library. 

@toadzky you could store Date/Calendar as a Long type, and use JodaTime in your project to handle this. Check it out this http://stackoverflow.com/a/17891061/2628278

**Comment by giorgioprovenzale** [comment]
Yes, thanks anyway, I solved using strings for Joda DateTime objects on DB

**Comment by toadzky** [comment]
@sibeliusseraphini of course you can, but that defeats the point of an ORM. same with @giorgioprovenzale storing it as a string. the string is better than the long tho (if you do ISO format) because it includes timezone too.

**Comment by sibeliusseraphini** [comment]
I don't think that is a good idea do add more deps to a library, this will only make the lib more heavy

**Comment by toadzky** [comment]
you can set dependencies as `provided` and check if the classes exist on the classpath. it's a pretty standard thing. 

in this case, joda is basically the standard library for dealing with dates and times pre-Java8 where the guy who wrote joda did the new java date/time apis. it's a pretty small library anyway, so requiring it or bundling it isn't that big of a deal.

**Pull request closed without merging**
