### PR TITLE
Added .idea/ to .gitignore

### PR DESCRIPTION
**Pull request by ishan1604**

### CODE REVIEW

**Comment by whoshuu** [comment]
Hey @ishan1604, I'd like to merge this in soon. Can you add `example/gen` and `*/local.properties` to .gitignore as well? I'd rather not put that under source control.

Also, is there a reason why you removed `sugar/library` as a library project in project.properties?

**Comment by ishan1604** [comment]
@whoshuu Thanks for looking into this. 
I'll add both the ``` example/gen ``` and ```*/local.properties``` to .gitignore.

I am not sure what made the the value from true to false in case of the library project, I'll fix and send a PR.

**Comment by ishan1604** [comment]
@whoshuu All changes done :)

**Comment by whoshuu** [comment]
Thanks, I'll get this in by the end of today!

**Pull request closed without merging**
