### PR TITLE
NullPointerException when try to add null foreign record fix

### PR DESCRIPTION
**Pull request by bioker**
Hello, i hope this fix will be useful for resolving that [issue](https://github.com/satyan/sugar/issues/676)

### CODE REVIEW

**Comment by JonatanSalas** [comment]
I will take a look at this when I get to home! Thank you for your PR!

**Comment by sibelius** [comment]
Could u fix the tests?

**Comment by bioker** [comment]
@sibelius, yes i could, what exactly need? Using empty constructor?

**Comment by bioker** [comment]
@sibelius, Ok. I look at the details of the check fail. Just I didn't before requests, don't understood at first time

**Comment by taynanb** [comment]
Hi, is it possible to use a version of the library with this problem fixed?

**Comment by sibelius** [comment]
looks good, tks

**Comment by taynanb** [comment]
Thank you so much, but has any beta release that can I use? Or only cloning project and using it as an module?

**Comment by sibelius** [comment]
@taynanb u just use master version for now: https://github.com/satyan/sugar#how-to-use-master-version

**Comment by taynanb** [comment]
@sibelius Thanks!

**Pull request merged**
